### ISSUE TITLE
大神，有优化后的性能更强的播放器吗？

### ISSUE THREAD

**Issue by liufeihong** [sonysuqin/WasmVideoPlayer#54]
测试过这款H265播放器，能够解码较低分辨率的视频，当解码720P和1080P视频的时候画面卡顿，解码很吃力。音频解码也不流畅，不知道大神最近有没有做进一步优化。

**Comment by tmkmk** [comment]
我这里编译不通过.提示找不到路径.你能知道什么问题吗?
Traceback (most recent call last):
  File "/home/roh/emsdk/upstream/emscripten/emconfigure.py", line 52, in <module>
    sys.exit(run())
  File "/home/roh/emsdk/upstream/emscripten/emconfigure.py", line 45, in run
    shared.Building.configure(sys.argv[1:])
  File "/home/roh/emsdk/upstream/emscripten/tools/shared.py", line 1396, in configure
    run_process(args, stdout=stdout, stderr=stderr, env=env, **kwargs)
  File "/home/roh/emsdk/upstream/emscripten/tools/shared.py", line 189, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1705, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './configure'

**Comment by EssLi** [comment]
同样的问题
