### ISSUE TITLE
Uncaught RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by dxdleikai** [sonysuqin/WasmVideoPlayer#55]
**背景：有个比较小的265视频可以播放，另个无法播放**
**报错信息：**

Uncaught RuntimeError: function signature mismatch
    at <anonymous>:wasm-function[931]:0xb8e8f
    at <anonymous>:wasm-function[46]:0x2663
    at <anonymous>:wasm-function[67]:0x6076
    at <anonymous>:wasm-function[184]:0x1d2d0
    at <anonymous>:wasm-function[2289]:0x1b4e65
    at <anonymous>:wasm-function[1404]:0x118fde
    at Q (<anonymous>:wasm-function[2212]:0x1a69d6)
    at Object.Module._openDecoder (https://roblin.cn/wasm/libffmpeg.js:1:92205)
    at Decoder.openDecoder (https://roblin.cn/wasm/decoder.js:48:22)
    at Decoder.processReq (https://roblin.cn/wasm/decoder.js:165:18)

**我用的视频和示例的视频格式相同，无法播放，mediaInfo如下：**
Metadata:     
    major_brand     : isom      
    minor_version   : 512         
    compatible_brands: isomiso2mp41  
    artist          : yinyuetai.com
    album           : Yinyuetai
    date            : 04/11/17 13:02:08
    encoder         : Lavf57.83.100
    comment         : Yinyuetai-1TR1166
  Duration: 00:02:53.80, start: 0.000000, bitrate: 3646 kb/s
    Stream #0:0(und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 3593 kb/s, 25 fps, 25 tbr, 12800 tbn, 25 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler

**求教**

**Comment by SakumotoJune** [comment]
我现在也出现了这个问题，请问你有进展了吗

**Comment by 812781385** [comment]
> 我现在也出现了这个问题，请问你有进展了吗？

我也遇到这个问题了，老铁有进展了吗

**Comment by dxdleikai** [comment]
> > 我现在也出现了这个问题，请问你有进展了吗？
> 
> 我也遇到这个问题了，老铁有进展了吗

没有解决，不能播放

**Comment by 812781385** [comment]
> > > 我现在也出现了这个问题，请问你有进展了吗？
> > 
> > 
> > 我也遇到这个问题了，老铁有进展了吗？
> 
> 没有解决，不能播放

我查阅了一些资料，应该是js不能解析i64，但是不知道怎么修改。ffmpeg被编译出来有个函数返回得i64，我想把wsam编成.wat，修改那里得i64改成i32，然后再编成wsam，不知道行不行。
