### ISSUE TITLE
播放H265视频文件，报错null function or function signature misamatch

### ISSUE THREAD

**Issue by goodgirlElena** [sonysuqin/WasmVideoPlayer#89]
libffmpeg.wasm:0x2c7e Uncaught RuntimeError: null function or function signature mismatch
    at seekCallback (libffmpeg.wasm:0x2c7e)
    at avio_seek (libffmpeg.wasm:0x4c39)
    at avio_skip (libffmpeg.wasm:0x4eb5)
    at mov_read_default (libffmpeg.wasm:0xcb6f)
    at mov_read_header (libffmpeg.wasm:0xe000)
    at avformat_open_input (libffmpeg.wasm:0x1ac91)
    at openDecoder (libffmpeg.wasm:0x304a)
    at Object.Module._openDecoder (libffmpeg.js:4904:81)
    at Decoder.openDecoder (decoder.js:48:22)
    at Decoder.processReq (decoder.js:165:18)

**Comment by goodgirlElena** [comment]
请问作者这个是什么原因呢，查看了视频的moov，是前置moov

**Comment by ShengMingZh** [comment]
0091d8c2:0x296f Uncaught RuntimeError: null function or function signature mismatch
    at 0091d8c2:0x296f
    at 0091d8c2:0xd9ed
    at 0091d8c2:0x47c7
    at Object._openDecoder (libffmpeg.js:1:13592)
    at Decoder.openDecoder (decoder.js:48:22)
    at Decoder.processReq (decoder.js:165:18)
    at self.onmessage (decoder.js:249:18)
遇到一样的问题，试了好多方法都没有搞定。
你上面的调用栈是怎么打出来的，要怎么编译才能打出函数名？
@goodgirlElena

**Comment by zsmsky** [comment]
@goodgirlElena
