### ISSUE TITLE
播放handbrake压制的mp4视频报错

### ISSUE THREAD

**Issue by juvham** [sonysuqin/WasmVideoPlayer#93]
播放用handbrake压制的编码格式h265的视频报错
Uncaught RuntimeError: null function or function signature mismatch
    at libffmpeg.wasm:0xb8e8f
    at libffmpeg.wasm:0x2663
    at libffmpeg.wasm:0x6076
    at libffmpeg.wasm:0x1d2d0
    at libffmpeg.wasm:0x1b4e65
    at libffmpeg.wasm:0x118fde
    at libffmpeg.wasm:0x1a69d6
    at Module._openDecoder (libffmpeg.js:4594:29)
    at Decoder.openDecoder (decoder.js:59:20)
    at Decoder.processReq (decoder.js:188:12)

**Comment by neepsh** [comment]
> 播放用handbrake压制的编码格式h265的视频报错 Uncaught RuntimeError: null function or function signature mismatch at libffmpeg.wasm:0xb8e8f at libffmpeg.wasm:0x2663 at libffmpeg.wasm:0x6076 at libffmpeg.wasm:0x1d2d0 at libffmpeg.wasm:0x1b4e65 at libffmpeg.wasm:0x118fde at libffmpeg.wasm:0x1a69d6 at Module._openDecoder (libffmpeg.js:4594:29) at Decoder.openDecoder (decoder.js:59:20) at Decoder.processReq (decoder.js:188:12)
看一下视频的moov box是不是前置的，这里需要是前置
